pkgcore/pkgcore

pkgcore/sync/bzr.py

Use 'bzr branch' rather than 'bzr get' since the latter is deprecated and no longer works correctly.

bzr sync: use modern 'bzr branch' command

---

pkgcore/ebuild/portage_conf.py

Strip leading slash from the world file path passed to os.path.join(),
as that causes it to ignore preceding parameters and therefore fail to
prepend root.

portage_config: fix prepending root to world file path

---

pkgcore/ebuild/portage_conf.py

This fixes load_make_conf and load_repos_conf to follow symlinks like
portage would do.

portage_conf: follow symlinks for sorted_scan calls

---

setup.py

This EEXISTs on me when reinstalling pkgcore from git in virtualenv :).

setup.py: Fix writing funcnames when dest exists already

---

pkgcore/cache/__init__.py
pkgcore/cache/flat_hash.py
pkgcore/ebuild/ebuild_src.py

These two make pkgcore-generated md5-cache useful for Portage. Well, it's not byte-exact still but it seems egencache is happy enough about it not to regenerate the whole cache.

Cache fixes

---

pkgcore/cache/flat_hash.py
pkgcore/operations/repo.py

As the summary says. I have used the simplest solution possible, and it seems not to cause any significant slowdown.
One small issue is that cache entries for broken packages are not removed but that's more of a corner case to handle.

pmaint regen: Clean up stale cache entries

---

bash/generate_global_func_list.bash

Fix PATH quoting in bash script to prevent failure on systems using
spaces in paths (such as OSX).

Fix PATH quoting in bash/generate_global_func_list.bash

---

pkgcore/package/conditionals.py

pquery: fix license containment checks errors

---

pkgcore/pkgsets/glsa.py
pkgcore/test/pkgsets/test_glsa.py

Fix the following issues in GLSA range handling:
- rgt with -r0 is perfectly valid (it matches -r1+),
- rle with -r0 is =, not ~,
- the glob code does not handle le, lt, gt, ge, so reject those.

[glsa] Fix handling ranges in GLSAs

---

pkgcore/ebuild/profiles.py
pkgcore/ebuild/repo_objs.py
pkgcore/test/ebuild/test_profiles.py

Add minimal syntax support for profile-formats = profile-set in profile
packages files. In the portage implementation, @profile packages do
not limit parallelization of builds in the way that @system packages do.
@chutz

ebuild/profiles: support profile-formats = profile-set

---

src/pkgcore/scripts/pmaint.py
tests/module/scripts/test_pmaint.py

The code was written assuming that the out/err is unbuffered-
which is not true.  That in turn leads to the underlying repo sync operations
(which are usually raw processes writing to the fd) having output intermixed.
Thus just force a flush before handing off to the repo operations, and sync upon
return from it.
Additionally, while I'm in here, cleanup the output a bit and drop the
fetish for forcing output to stderr.

Fix pmaint sync buffering and flushing.

---

ebd/ebuild.bash
src/pkgcore/ebuild/ebd.py

Start pkg_* phases in a dedicated empty directory that's recreated
for every phase invoked.  This is required by EAPI 8 but since earlier
EAPIs allow any starting directory, it's fine to do it for all EAPIs.
Fixes #313

Start pkg_* phases in a dedicated empty directory

---

src/pkgcore/ebuild/cpv.py
tests/ebuild/test_cpv.py

Fix the package name verification logic not to incorrectly reject
packages that resemble a version number or that contain a series
of hyphens.  Document the algorithm better and add more tests for corner
cases.

pkgcore.ebuild.cpv: fix isvalid_pkg_name() logic

---

src/pkgcore/ebuild/eclass.py
tests/ebuild/test_eclass.py

Add support for @PROVIDES tag that replaces the pkgcore-specific
@INDIRECT_ECLASSES.  Add an alias attribute to preserve backwards
compatibility for the time being.
(pending https://archives.gentoo.org/gentoo-dev/message/bdc1a5c676cbd42c1362665f7d03e873)

ebuild.eclass: Support @PROVIDES in place of @INDIRECT_ECLASSES

---

NEWS.rst
src/pkgcore/cache/__init__.py

Detect cache entries missing INHERIT key and force cache invalidation
for them.  This fixes false positives from pkgcheck's InheritsCheck
if the repository contains up-to-date metadata cache entries generated
by Portage or PkgCore prior to the introduction of INHERIT key.
If _eclasses_ are non-empty, then we can reasonably assume that INHERIT
must be non-empty as well (i.e. at least one eclass was inherited
directly).

cache: invalidate cache entries without INHERIT key

---

ebd/eapi/8/src_configure.bash

Update the EAPI 8 --disable-static to be emitted when either
--disable-static or --enable-static occurs in configure --help output.
This is necessary to handle libtool packages correctly, and this is how
it was initially implemented in Portage.  PMS is being updated to match.
Bug: https://bugs.gentoo.org/814368

ebd: update EAPI 8 --disable-static rule per PMS update

---

src/pkgcore/ebuild/domain.py
src/pkgcore/ebuild/repo_objs.py
src/pkgcore/ebuild/repository.py
tests/ebuild/test_repository.py

A repo can define a group of licenses which inherits groups from
masters repos. In previous implementation, this was forbidden and
was printing weird output error.
The new implementation makes Licenses object directly support
master repos inheritance. No one had used the Licenses class, but
the OverlayedLicenses class, which the new implementation mimics
directly in one merged class, with correct ordering of evaluation.
Resolves: https://github.com/pkgcore/pkgcore/issues/335
Signed-off-by: Arthur Zamarin <arthurzam@gentoo.org>
---
TODO:

ebuild.repository: fix inheriting license groups

---

src/pkgcore/ebuild/atom.py
tests/ebuild/test_atom.py

We don't have a lot of users of the property no_usedeps for atom, so it was missed that we were ignoring the subslot value in the return. By including it, we are fixing an issue that was found with `VirtualKeywordsUpdate` in `virtual/podofo-build`.
Tested over at `::gentoo` repo, and it indeed fixed it for `virtual/podofo-build`.
Resolves: https://github.com/pkgcore/pkgcheck/issues/411

ebuild/atom.py: atom.no_usedeps should include subslot

---

src/pkgcore/ebuild/portage_conf.py
src/pkgcore/sync/rsync.py

When using rsync as sync type for a repository, if in `make.conf` `PORTAGE_RSYNC_INITIAL_TIMEOUT` was defined, it had crashed the code, as it was saving it into the wrong field name.
Bug: https://bugs.gentoo.org/872116

portage_conf: fix timeout settings for rsync

---

src/pkgcore/ebuild/domain.py
src/pkgcore/ebuild/inspect_profile.py
src/pkgcore/ebuild/profiles.py
src/pkgcore/ebuild/repo_objs.py
tests/ebuild/test_profiles.py

Add support for `profile-bashrcs` profile format, which adds support for per-profile bashrc mechanism `package.bashrc`, which enables to specify per restriction the extra bashrc files to run.
See portage(5) for format details.

profiles: support package.bashrc files

---

bin/patom
doc/conf.py
src/pkgcore/scripts/patom.py
tests/scripts/test_patom.py

Requested by @mgorny
The args and docs are taken from `atom`, but the format will have different names.
I still have various extra arguments I want to implement, but this is a start.

patom: new command

---

pyproject.toml
src/pkgcore/restrictions/required_use.py
tests/restrictions/test_required_use.py

Based on new `snakeoil.constraints`, this adds a solver which can build satisfying USE flag combinations for a given set of REQUIRED_USE restricts. This will be used by new tool `pkgdev tatt`.

Add REQUIRED_USE satisfaction solver

---

src/pkgcore/ebuild/domain.py
src/pkgcore/ebuild/misc.py
tests/ebuild/test_domain.py

Add support for `-*` and `USE_EXPAND: -*` syntax. Allow this syntax, and update incremental computation of resulting use combination.
Resolves: https://github.com/pkgcore/pkgcore/issues/393
I'm not sure I've solved it in the ideal way, on the fast way. From multiple tests, it seems to work, but this part of pkgcore is still hard for me to understand (especially the change in `incremental_chunked`).

domain: support `-*` in use as previous removal

---

src/pkgcore/pytest/plugin.py
src/pkgcore/repository/configured.py
src/pkgcore/repository/filtered.py
src/pkgcore/repository/prototype.py
tests/repository/test_filtered.py

The commits carry detailed info for each change.  Summarizing:
* Downstream usage of the pytest plugin had assumption about environment hygiene ($HOME being sanitized) that wasn't true.  That's fixed.  That primarily impacted test validation of pkgdev.
* Repository prototype as converted to an ABC so any derivatives that don't override abstract methods get flagged; both filtered (actually broke) and configured (false positive, but best to be explicit) were caught via this.
* * For filtered, the `.{category,package,versions}` API was broken via `super().__init__()` not being invoked.  This is fixed, and proper implementations of the underlying `_get_.*` methods was added, along with tests.
*  `prototype.tree._get_{category,packages,versions}` had a requirement that child implementations …

Hygenic test fix + repository typing cleanup + fixes

---

.git-blame-ignore-revs
pyproject.toml

Check the commit messages for overly verbose explanations of what/where/why for the author changes, including an explanation of why tracking this sort of copyright (and how it gets obscured) is relevant.  Fundamentally calling out folks who did the work- even if they don't care now- is part of attracting contributors.
Roughly:
* for the git blame ignore list, this was a manual audit.  For spot checking, it was good enough for me to trace certain things back to '04, which is sufficient for being able to reach back and identify why I fucked something up.
* For mgorny addition to authors, trace the history, arguably it's time.  Worst case, this is a way to add a sense of responsibility to induce future contributions.
* For marienz- VCS and history obscures it, but in tracing code, there are …

Update the git rev blame ignore list, add marienz and mgórny

---

doc/conf.py
pyproject.toml

intersphinx is used to do linkage between projects- pkgcore referring to snakeoil documentation for example.
These links are long since old/dead, thus need fixing.
See https://github.com/pkgcore/pkgcore/actions/runs/7656999844/job/20874145430 for an example of the failure.

Correct fix intersphinx doc linkage, automate maintenance of it.
